import React, { useState } from "react";
import { useLang } from "../components/LanguageContext";
import { AlertTriangle, Zap, Users, Bomb, Radio, ChevronDown, ChevronUp, Shield, Crosshair, Waves, Mountain, Flame, Wind } from "lucide-react";

const content = {
  es: {
    title: "AMENAZAS ACTIVAS",
    subtitle: "Identifica la amenaza. Actúa en los primeros 30 segundos. Cada segundo cuenta.",
    threats: [
      { id: "missile", icon: Bomb, color: "text-red-500", bgColor: "bg-red-500/10", borderColor: "border-red-500/30", level: "CRÍTICO", title: "Ataque de Misil Balístico", warning: "Tendrás entre 4 y 14 minutos de aviso previo si existe sistema de alerta.", steps: ["Al escuchar la sirena: NO pierdas ni un segundo en mirar por la ventana.", "Dirígete INMEDIATAMENTE al sótano o al cuarto interior más bajo.", "Aléjate de ventanas, cristales y paredes exteriores.", "Cúbrete bajo una mesa resistente o junto a una pared interior.", "Si estás en el exterior: tumba te en el suelo, cubre tu cabeza.", "NO uses el ascensor. Usa las escaleras.", "Permanece en el refugio al menos 24h tras el impacto.", "Escucha la radio de emergencia. No salgas hasta autorización oficial."], extra: "Los misiles hipersónicos actuales viajan a Mach 5+. No habrá tiempo de pensar. Solo de reaccionar." },
      { id: "infantry", icon: Users, color: "text-orange-500", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "ALTO", title: "Ataque de Infantería / Tirador Activo", warning: "Puede ocurrir sin previo aviso en zonas urbanas.", steps: ["CORRE: Si hay salida segura, huye dejando todo atrás.", "ESCÓNDETE: Si no puedes huir, busca cobertura densa (no solo ocultación).", "Cierra puertas con llave. Bloquea con muebles pesados.", "Apaga luces. Silencia el móvil completamente.", "Llama al 112 (Europa) o 911 (América) cuando sea seguro hacerlo.", "PELEA como último recurso: objetos pesados, sillas, extintores.", "No te muevas hasta confirmación policial de zona segura.", "Levanta las manos al ser rescatado. Sigue instrucciones exactas."], extra: "En conflicto armado activo, las reglas de combate cambian. La disciplina lo es todo." },
      { id: "emp", icon: Zap, color: "text-yellow-500", bgColor: "bg-yellow-500/10", borderColor: "border-yellow-500/30", level: "ALTO", title: "Pulso Electromagnético (EMP)", warning: "Un EMP puede inutilizar toda la electrónica en cientos de kilómetros.", steps: ["Si toda la electrónica falla de golpe: asume un EMP. No entres en pánico.", "Los vehículos modernos dejarán de funcionar. Ve a pie.", "Comunícate solo en persona o mediante radios analógicas.", "El agua de grifo puede fallar (bombas eléctricas). Usa reservas.", "Los hospitales sin generadores fallarán. Activa tu kit médico.", "Guarda una radio analógica de pilas en tu mochila SOS.", "Mantén efectivo físico: los cajeros y TPV no funcionarán.", "Establece punto de reunión familiar PREVIO. No hay forma de llamar."], extra: "Una sola ojiva nuclear detonada a 400km de altitud puede apagar la red eléctrica de un país entero." },
      { id: "chemical", icon: Radio, color: "text-green-500", bgColor: "bg-green-500/10", borderColor: "border-green-500/30", level: "SEVERO", title: "Ataque Químico / Radiológico", warning: "Invisible, inodoro en muchos casos. Devastador en minutos.", steps: ["Ante olor a almendras, ajo o huevo podrido: abandona la zona CORRIENDO.", "Cubre nariz y boca con tela húmeda como medida temporal.", "Busca altura: muchos agentes químicos son más densos que el aire.", "En ataque radiológico: pon máxima distancia entre tú y la fuente.", "Sella ventanas y puertas con cinta adhesiva si debes quedarte.", "Ducharse con agua y jabón elimina hasta el 80% de contaminación externa.", "No toques a víctimas sin protección. Podrías contaminarte.", "Escucha instrucciones oficiales de evacuación o refugio."], extra: "El yodo de potasio solo protege la tiroides en ataques radiológicos. Tenerlo no te hace inmune." },
      { id: "terrorist", icon: Crosshair, color: "text-purple-400", bgColor: "bg-purple-500/10", borderColor: "border-purple-500/30", level: "CRÍTICO", title: "Ataque Terrorista (Explosivo / Masivo)", warning: "Puede producirse sin aviso en lugares concurridos: metro, mercados, eventos, transportes.", steps: ["Si escuchas una explosión: cúbrete INMEDIATAMENTE en el suelo, protege la cabeza.", "No mires hacia el origen: una segunda explosión es táctica habitual para causar más bajas.", "Aléjate en dirección CONTRARIA al origen, agachado, pegado a paredes.", "No uses el ascensor ni te aglomeres en salidas de emergencia.", "Si hay heridos cerca y es seguro: aplica presión directa en hemorragias graves.", "Llama al 112 / 911 en cuanto estés en zona segura.", "No difundas rumores ni fotos: satura las líneas de emergencia.", "Obedece estrictamente las instrucciones de los cuerpos de seguridad.", "Permanece alejado del edificio/zona: riesgo de derrumbe y explosiones secundarias."], extra: "Los ataques en dos fases (primera explosión + segunda cuando llega la ayuda) son una táctica documentada. Espera siempre 5 minutos antes de acercarte a ayudar." },
      { id: "tsunami", icon: Waves, color: "text-blue-400", bgColor: "bg-blue-500/10", borderColor: "border-blue-500/30", level: "CRÍTICO", title: "Tsunami", warning: "El mar que se retira repentinamente es la señal más clara. Tienes minutos para actuar.", steps: ["Si el mar retrocede drásticamente o sientes un terremoto costero fuerte: huye INMEDIATAMENTE tierra adentro.", "Dirígete a zonas elevadas (colinas, edificios altos de hormigón) sin detenerte.", "No esperes la alerta oficial: cada segundo cuenta.", "Abandona vehículos si el tráfico se detiene. Ve a pie hacia altura.", "La primera ola no es la más peligrosa: puede haber múltiples olas durante horas.", "No regreses a la costa hasta aviso oficial de autoridades.", "Si estás en un barco en mar abierto: aléjate de la costa hacia aguas profundas.", "Escucha la radio de emergencia para actualizaciones."], extra: "Un tsunami puede viajar a 800 km/h en aguas profundas. Al acercarse a la costa reduce velocidad pero gana altura. Las olas pueden superar los 30 metros." },
      { id: "earthquake", icon: Mountain, color: "text-amber-500", bgColor: "bg-amber-500/10", borderColor: "border-amber-500/30", level: "ALTO", title: "Terremoto", warning: "Sin aviso previo. El movimiento puede durar de segundos a minutos.", steps: ["Durante el sismo: AGÁCHATE, CÚBRETE bajo una mesa resistente y SUJÉTATE.", "Aléjate de ventanas, estanterías, electrodomésticos y paredes exteriores.", "Si estás en exterior: aléjate de edificios, postes y cables eléctricos.", "NO uses el ascensor. NO corras hacia las salidas durante el temblor.", "Si estás en cama: quédate, cúbrete la cabeza con la almohada.", "Tras el sismo: corta el gas si hueles fuga. No enciendas cerillas ni interruptores.", "Sal del edificio con calma una vez termine el temblor. Busca zona abierta.", "Prepárate para réplicas: pueden ser tan fuertes como el sismo principal."], extra: "La regla 'triángulo de vida' es un mito peligroso. Agacharse bajo una mesa resistente es el protocolo científicamente validado (Drop, Cover, Hold On)." },
      { id: "wildfire", icon: Flame, color: "text-orange-400", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "ALTO", title: "Incendio Forestal", warning: "Puede avanzar más rápido que un corredor olímpico. La evacuación temprana es la única defensa real.", steps: ["Ante alerta de incendio en tu zona: evacúa ANTES de que sea obligatorio. No esperes.", "Cierra puertas, ventanas y rejillas de ventilación al salir (reduce entrada de humo).", "Sigue rutas de evacuación oficiales. No improvises.", "Si te sorprende el fuego en vehículo: aparca, luces encendidas, tímbrate bocina, cúbrete con manta ignífuga.", "Si estás a pie: busca la zona ya quemada (el fuego no vuelve a pasar por donde ya quemó).", "Protege las vías respiratorias: tela húmeda sobre nariz y boca.", "Nunca huyas cuesta arriba: el fuego sube más rápido que tú.", "Avisa a bomberos de tu posición cuando sea seguro usar el teléfono."], extra: "Un incendio forestal puede avanzar a 20 km/h en terreno llano y hasta 100 km/h con viento fuerte. El humo mata antes que las llamas." },
      { id: "volcano", icon: Mountain, color: "text-red-400", bgColor: "bg-red-500/10", borderColor: "border-red-400/30", level: "SEVERO", title: "Erupción Volcánica", warning: "Las coladas de piroclastos viajan a 700 km/h. La única protección es la evacuación temprana.", steps: ["Ante alerta volcánica: evacúa inmediatamente siguiendo rutas oficiales ALEJADAS del volcán.", "Nunca intentes fotografiar la erupción desde zonas de riesgo.", "Cubre nariz y boca con mascarilla N95 o tela húmeda: las cenizas destruyen los pulmones.", "Protege ojos con gafas herméticas: las cenizas causan abrasión corneal grave.", "Si caen cenizas: quédate en interiores, sella ventanas y puertas con cinta.", "Las cenizas acumuladas pueden derrumbar techos: sal si supera 10 cm de acumulación.", "Evita valles y cauces de ríos: los lahares (flujos de lodo volcánico) los siguen.", "No regreses a la zona de exclusión hasta autorización oficial."], extra: "Los gases volcánicos (SO₂, CO₂, H₂S) son invisibles y mortales. Una zona que parece segura puede tener concentraciones letales a nivel del suelo." },
      { id: "tornado", icon: Wind, color: "text-teal-400", bgColor: "bg-teal-500/10", borderColor: "border-teal-500/30", level: "ALTO", title: "Tornado", warning: "Un tornado F5 genera vientos de más de 300 km/h. Destruye edificios de hormigón en segundos.", steps: ["Ante sirena de tornado: busca INMEDIATAMENTE el sótano o habitación interior en planta baja.", "Aléjate de ventanas. Protege la cabeza y el cuello con los brazos o un casco.", "Si estás en casa sin sótano: baño interior, armario central o pasillo sin ventanas.", "Nunca busques refugio bajo un puente: crea efecto túnel que amplifica el viento.", "Si estás en vehículo: NO intentes escapar del tornado en coche. Busca edificio sólido.", "Si no hay edificio: tumba te en una zanja o depresión del terreno, lejos de árboles.", "Tras el tornado: cuidado con cables eléctricos caídos, gas y estructuras inestables.", "Escucha la radio: pueden formarse tornados adicionales en la misma tormenta."], extra: "El 'cielo verde' antes de una tormenta severa es una señal de alerta de tornado. Si el aire se vuelve súbitamente quieto tras granizo intenso: actúa de inmediato." },
    ],
  },
  en: {
    title: "ACTIVE THREATS",
    subtitle: "Identify the threat. Act in the first 30 seconds. Every second counts.",
    threats: [
      { id: "missile", icon: Bomb, color: "text-red-500", bgColor: "bg-red-500/10", borderColor: "border-red-500/30", level: "CRITICAL", title: "Ballistic Missile Attack", warning: "You'll have 4 to 14 minutes of warning if an alert system exists.", steps: ["When you hear the siren: do NOT waste a second looking out the window.", "Go IMMEDIATELY to the basement or lowest interior room.", "Stay away from windows, glass and exterior walls.", "Cover under a sturdy table or against an interior wall.", "If outside: lie flat on the ground, cover your head.", "Do NOT use the elevator. Use the stairs.", "Stay in shelter at least 24h after impact.", "Listen to the emergency radio. Do not leave until official clearance."], extra: "Current hypersonic missiles travel at Mach 5+. There will be no time to think. Only to react." },
      { id: "infantry", icon: Users, color: "text-orange-500", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "HIGH", title: "Infantry Attack / Active Shooter", warning: "Can occur without warning in urban areas.", steps: ["RUN: If there's a safe exit, flee leaving everything behind.", "HIDE: If you can't flee, find dense cover (not just concealment).", "Lock doors. Block with heavy furniture.", "Turn off lights. Silence your phone completely.", "Call 911 (US) or local emergency when safe to do so.", "FIGHT as a last resort: heavy objects, chairs, fire extinguishers.", "Do not move until police confirm the area is clear.", "Raise hands when rescued. Follow exact instructions."], extra: "In active armed conflict, rules change. Discipline is everything." },
      { id: "emp", icon: Zap, color: "text-yellow-500", bgColor: "bg-yellow-500/10", borderColor: "border-yellow-500/30", level: "HIGH", title: "Electromagnetic Pulse (EMP)", warning: "An EMP can disable all electronics within hundreds of kilometers.", steps: ["If all electronics fail at once: assume an EMP. Do not panic.", "Modern vehicles will stop working. Travel on foot.", "Communicate only in person or via analog radios.", "Tap water may fail (electric pumps). Use reserves.", "Hospitals without generators will fail. Activate your medical kit.", "Keep an analog battery-powered radio in your go-bag.", "Keep physical cash: ATMs and card terminals won't work.", "Establish a PRIOR family meeting point. There's no way to call."], extra: "A single nuclear warhead detonated 400km above can shut down the power grid of an entire country." },
      { id: "chemical", icon: Radio, color: "text-green-500", bgColor: "bg-green-500/10", borderColor: "border-green-500/30", level: "SEVERE", title: "Chemical / Radiological Attack", warning: "Invisible, often odorless. Devastating within minutes.", steps: ["Smell of almonds, garlic or rotten eggs: leave the area RUNNING.", "Cover nose and mouth with wet cloth as a temporary measure.", "Seek height: many chemical agents are denser than air.", "In a radiological attack: maximize distance from the source.", "Seal windows and doors with tape if you must shelter in place.", "Showering with soap removes up to 80% of external contamination.", "Do not touch victims without protection. You could be contaminated.", "Follow official evacuation or shelter-in-place instructions."], extra: "Potassium iodide only protects the thyroid in radiological attacks. Having it does not make you immune." },
      { id: "terrorist", icon: Crosshair, color: "text-purple-400", bgColor: "bg-purple-500/10", borderColor: "border-purple-500/30", level: "CRITICAL", title: "Terrorist Attack (Explosive / Mass Casualty)", warning: "Can occur without warning in crowded places: subway, markets, events, transport hubs.", steps: ["If you hear an explosion: take cover IMMEDIATELY on the ground, protect your head.", "Do not look toward the origin: a second blast is a common tactic to cause more casualties.", "Move AWAY from the origin, crouched, staying close to walls.", "Do not use elevators or crowd emergency exits.", "If there are nearby injured and it is safe: apply direct pressure to severe bleeding.", "Call 911 / local emergency as soon as you reach a safe area.", "Do not spread rumors or photos: it overloads emergency lines.", "Strictly follow instructions from security forces.", "Stay away from the building/area: risk of collapse and secondary explosions."], extra: "Two-phase attacks (first explosion + second when help arrives) are a documented tactic. Always wait 5 minutes before approaching to help." },
      { id: "tsunami", icon: Waves, color: "text-blue-400", bgColor: "bg-blue-500/10", borderColor: "border-blue-500/30", level: "CRITICAL", title: "Tsunami", warning: "The sea suddenly retreating is the clearest warning sign. You have minutes to act.", steps: ["If the sea retreats drastically or you feel a strong coastal earthquake: flee IMMEDIATELY inland.", "Head to high ground (hills, tall concrete buildings) without stopping.", "Do not wait for official alerts: every second counts.", "Abandon vehicles if traffic stops. Go on foot toward higher ground.", "The first wave is not the most dangerous: multiple waves can strike over hours.", "Do not return to the coast until official all-clear is issued.", "If you are on a boat in open sea: move away from shore into deep water.", "Listen to emergency radio for updates."], extra: "A tsunami can travel at 800 km/h in deep water. As it approaches shore it slows but gains height. Waves can exceed 30 meters." },
      { id: "earthquake", icon: Mountain, color: "text-amber-500", bgColor: "bg-amber-500/10", borderColor: "border-amber-500/30", level: "HIGH", title: "Earthquake", warning: "No prior warning. Shaking can last from seconds to minutes.", steps: ["During the quake: DROP, COVER under a sturdy table, and HOLD ON.", "Stay away from windows, shelves, appliances and exterior walls.", "If outdoors: move away from buildings, poles and power lines.", "Do NOT use elevators. Do NOT run toward exits during shaking.", "If in bed: stay there, cover your head with a pillow.", "After the quake: shut off gas if you smell a leak. Do not use flames or switches.", "Exit the building calmly once shaking stops. Find an open area.", "Prepare for aftershocks: they can be as strong as the main quake."], extra: "The 'triangle of life' is a dangerous myth. Dropping under a sturdy table is the scientifically validated protocol (Drop, Cover, Hold On)." },
      { id: "wildfire", icon: Flame, color: "text-orange-400", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "HIGH", title: "Wildfire", warning: "Can advance faster than an Olympic sprinter. Early evacuation is the only real defense.", steps: ["On wildfire alert in your area: evacuate BEFORE it becomes mandatory. Do not wait.", "Close doors, windows and vents when leaving (slows smoke entry).", "Follow official evacuation routes. Do not improvise.", "If caught in a vehicle: park, lights on, horn blaring, cover with fire blanket.", "If on foot: seek already-burned area (fire won't pass through twice).", "Protect your airways: wet cloth over nose and mouth.", "Never flee uphill: fire climbs faster than you.", "Alert firefighters of your position when safe to use your phone."], extra: "A wildfire can advance at 20 km/h on flat terrain and up to 100 km/h with strong winds. Smoke kills before flames do." },
      { id: "volcano", icon: Mountain, color: "text-red-400", bgColor: "bg-red-500/10", borderColor: "border-red-400/30", level: "SEVERE", title: "Volcanic Eruption", warning: "Pyroclastic flows travel at 700 km/h. Early evacuation is the only protection.", steps: ["On volcanic alert: evacuate immediately following official routes AWAY from the volcano.", "Never attempt to photograph the eruption from risk zones.", "Cover nose and mouth with N95 mask or wet cloth: ash destroys lungs.", "Protect eyes with sealed goggles: ash causes severe corneal abrasion.", "If ash is falling: stay indoors, seal windows and doors with tape.", "Accumulated ash can collapse roofs: evacuate if buildup exceeds 10 cm.", "Avoid valleys and riverbeds: lahars (volcanic mudflows) follow them.", "Do not return to the exclusion zone until official clearance."], extra: "Volcanic gases (SO₂, CO₂, H₂S) are invisible and lethal. An area that looks safe may have deadly concentrations at ground level." },
      { id: "tornado", icon: Wind, color: "text-teal-400", bgColor: "bg-teal-500/10", borderColor: "border-teal-500/30", level: "HIGH", title: "Tornado", warning: "An F5 tornado generates winds over 300 km/h. It destroys concrete buildings in seconds.", steps: ["On tornado siren: IMMEDIATELY seek the basement or an interior room on the ground floor.", "Stay away from windows. Protect your head and neck with your arms or a helmet.", "If in a house without a basement: interior bathroom, central closet or windowless hallway.", "Never shelter under a bridge: it creates a wind tunnel effect amplifying the wind.", "If in a vehicle: do NOT try to outrun the tornado. Find a solid building.", "If no building is available: lie flat in a ditch or low ground, away from trees.", "After the tornado: beware of downed power lines, gas leaks and unstable structures.", "Listen to radio: additional tornadoes can form in the same storm system."], extra: "A 'green sky' before a severe storm is a tornado warning sign. If the air suddenly goes quiet after heavy hail: act immediately." },
    ],
  },
};

export default function Threats() {
  const { lang } = useLang();
  const c = content[lang] || content["en"];
  const [openId, setOpenId] = useState("missile");

  return (
    <div className="max-w-3xl mx-auto px-6 py-10">
      <div className="flex items-center gap-2 mb-2">
        <div className="w-2 h-2 bg-red-500 rounded-full alert-pulse" />
        <span className="text-red-500 text-xs font-bold tracking-widest uppercase">{lang === "es" ? "PROTOCOLO DE AMENAZA" : "THREAT PROTOCOL"}</span>
      </div>
      <h1 className="font-military text-3xl lg:text-4xl text-foreground tracking-widest mb-2">{c.title}</h1>
      <p className="text-muted-foreground text-sm mb-8 leading-relaxed">{c.subtitle}</p>
      <div className="space-y-3">
        {c.threats.map((threat) => {
          const Icon = threat.icon;
          const isOpen = openId === threat.id;
          return (
            <div key={threat.id} className={`border rounded overflow-hidden ${threat.borderColor}`}>
              <button onClick={() => setOpenId(isOpen ? null : threat.id)} className={`w-full flex items-center justify-between p-5 ${threat.bgColor} hover:opacity-90 transition-all`}>
                <div className="flex items-center gap-4">
                  <Icon className={`w-6 h-6 ${threat.color}`} />
                  <div className="text-left">
                    <div className={`text-[10px] font-bold tracking-widest ${threat.color} mb-0.5`}>{lang === "es" ? "NIVEL" : "LEVEL"}: {threat.level}</div>
                    <div className="font-military text-sm text-foreground tracking-wide">{threat.title}</div>
                  </div>
                </div>
                {isOpen ? <ChevronUp className="w-4 h-4 text-muted-foreground" /> : <ChevronDown className="w-4 h-4 text-muted-foreground" />}
              </button>
              {isOpen && (
                <div className="p-5 bg-card border-t border-border">
                  <div className="flex items-start gap-2 mb-5 p-3 bg-accent/10 border border-accent/30 rounded">
                    <AlertTriangle className="w-4 h-4 text-accent mt-0.5 shrink-0" />
                    <p className="text-xs text-accent leading-relaxed">{threat.warning}</p>
                  </div>
                  <h3 className="text-xs font-bold text-muted-foreground tracking-widest uppercase mb-3">{lang === "es" ? "PROTOCOLO DE ACCIÓN" : "ACTION PROTOCOL"}</h3>
                  <ol className="space-y-2 mb-5">
                    {threat.steps.map((step, i) => (
                      <li key={i} className="flex items-start gap-3">
                        <span className="text-primary font-military text-sm font-bold shrink-0 w-5">{i + 1}.</span>
                        <span className="text-sm text-foreground leading-relaxed">{step}</span>
                      </li>
                    ))}
                  </ol>
                  <div className="p-3 bg-secondary rounded border border-border">
                    <div className="flex items-center gap-2 mb-1">
                      <Shield className="w-3 h-3 text-muted-foreground" />
                      <span className="text-[10px] text-muted-foreground uppercase tracking-widest font-bold">{lang === "es" ? "DATO TÁCTICO" : "TACTICAL NOTE"}</span>
                    </div>
                    <p className="text-xs text-muted-foreground italic leading-relaxed">{threat.extra}</p>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
