import React, { useState } from "react";
import { useLang } from "../components/LanguageContext";
import { getLangContent } from "../utils/langFallback";
import { AlertTriangle, Zap, Users, Bomb, Radio, ChevronDown, ChevronUp, Shield, Crosshair, Waves, Mountain, Flame, Wind } from "lucide-react";

const uiLabels = {
  es: { title: "AMENAZAS ACTIVAS", subtitle: "Identifica la amenaza. Actúa en los primeros 30 segundos. Cada segundo cuenta.", levelLabel: "NIVEL", protocolLabel: "PROTOCOLO DE ACCIÓN", noteLabel: "DATO TÁCTICO", warningLabel: "ADVERTENCIA", tagline: "PROTOCOLO DE AMENAZA" },
  en: { title: "ACTIVE THREATS", subtitle: "Identify the threat. Act in the first 30 seconds. Every second counts.", levelLabel: "LEVEL", protocolLabel: "ACTION PROTOCOL", noteLabel: "TACTICAL NOTE", warningLabel: "WARNING", tagline: "THREAT PROTOCOL" },
  fr: { title: "MENACES ACTIVES", subtitle: "Identifiez la menace. Agissez dans les 30 premières secondes. Chaque seconde compte.", levelLabel: "NIVEAU", protocolLabel: "PROTOCOLE D'ACTION", noteLabel: "NOTE TACTIQUE", warningLabel: "AVERTISSEMENT", tagline: "PROTOCOLE DE MENACE" },
  pt: { title: "AMEAÇAS ATIVAS", subtitle: "Identifique a ameaça. Aja nos primeiros 30 segundos. Cada segundo conta.", levelLabel: "NÍVEL", protocolLabel: "PROTOCOLO DE AÇÃO", noteLabel: "NOTA TÁTICA", warningLabel: "AVISO", tagline: "PROTOCOLO DE AMEAÇA" },
  it: { title: "MINACCE ATTIVE", subtitle: "Identifica la minaccia. Agisci nei primi 30 secondi. Ogni secondo conta.", levelLabel: "LIVELLO", protocolLabel: "PROTOCOLLO D'AZIONE", noteLabel: "NOTA TATTICA", warningLabel: "AVVERTIMENTO", tagline: "PROTOCOLLO MINACCIA" },
  ar: { title: "التهديدات النشطة", subtitle: "حدد التهديد. تصرف في أول 30 ثانية. كل ثانية تهم.", levelLabel: "المستوى", protocolLabel: "بروتوكول العمل", noteLabel: "ملاحظة تكتيكية", warningLabel: "تحذير", tagline: "بروتوكول التهديد" },
  zh: { title: "活跃威胁", subtitle: "识别威胁。在前30秒内采取行动。每一秒都至关重要。", levelLabel: "级别", protocolLabel: "行动规程", noteLabel: "战术提示", warningLabel: "警告", tagline: "威胁规程" },
};

const threatData = {
  es: [
    { id: "missile", icon: Bomb, color: "text-red-500", bgColor: "bg-red-500/10", borderColor: "border-red-500/30", level: "CRÍTICO", title: "Ataque de Misil Balístico", warning: "Tendrás entre 4 y 14 minutos de aviso previo si existe sistema de alerta.", steps: ["Al escuchar la sirena: NO pierdas ni un segundo en mirar por la ventana.", "Dirígete INMEDIATAMENTE al sótano o al cuarto interior más bajo.", "Aléjate de ventanas, cristales y paredes exteriores.", "Cúbrete bajo una mesa resistente o junto a una pared interior.", "Si estás en el exterior: túmbate en el suelo, cubre tu cabeza.", "NO uses el ascensor. Usa las escaleras.", "Permanece en el refugio al menos 24h tras el impacto.", "Escucha la radio de emergencia. No salgas hasta autorización oficial."], extra: "Los misiles hipersónicos actuales viajan a Mach 5+. No habrá tiempo de pensar. Solo de reaccionar." },
    { id: "infantry", icon: Users, color: "text-orange-500", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "ALTO", title: "Tirador Activo / Ataque de Infantería", warning: "Puede ocurrir sin previo aviso en zonas urbanas.", steps: ["CORRE: Si hay salida segura, huye dejando todo atrás.", "ESCÓNDETE: Si no puedes huir, busca cobertura densa.", "Cierra puertas con llave. Bloquea con muebles pesados.", "Apaga luces. Silencia el móvil completamente.", "Llama al 112 cuando sea seguro hacerlo.", "PELEA como último recurso: objetos pesados, sillas, extintores.", "No te muevas hasta confirmación policial de zona segura.", "Levanta las manos al ser rescatado. Sigue instrucciones exactas."], extra: "En conflicto armado activo, las reglas de combate cambian. La disciplina lo es todo." },
    { id: "emp", icon: Zap, color: "text-yellow-500", bgColor: "bg-yellow-500/10", borderColor: "border-yellow-500/30", level: "ALTO", title: "Pulso Electromagnético (EMP)", warning: "Un EMP puede inutilizar toda la electrónica en cientos de kilómetros.", steps: ["Si toda la electrónica falla de golpe: asume un EMP. No entres en pánico.", "Los vehículos modernos dejarán de funcionar. Ve a pie.", "Comunícate solo en persona o mediante radios analógicas.", "El agua de grifo puede fallar. Usa reservas.", "Mantén efectivo físico: los cajeros no funcionarán.", "Establece punto de reunión familiar PREVIO. No hay forma de llamar.", "Guarda una radio analógica de pilas en tu mochila SOS.", "Los hospitales sin generadores fallarán. Activa tu kit médico."], extra: "Una sola ojiva nuclear detonada a 400km de altitud puede apagar la red eléctrica de un país entero." },
    { id: "chemical", icon: Radio, color: "text-green-500", bgColor: "bg-green-500/10", borderColor: "border-green-500/30", level: "SEVERO", title: "Ataque Químico / Radiológico", warning: "Invisible, inodoro en muchos casos. Devastador en minutos.", steps: ["Ante olor a almendras, ajo o huevo podrido: abandona la zona CORRIENDO.", "Cubre nariz y boca con tela húmeda como medida temporal.", "Busca altura: muchos agentes químicos son más densos que el aire.", "En ataque radiológico: pon máxima distancia entre tú y la fuente.", "Sella ventanas y puertas con cinta adhesiva si debes quedarte.", "Ducharse con agua y jabón elimina hasta el 80% de contaminación externa.", "No toques a víctimas sin protección. Podrías contaminarte.", "Escucha instrucciones oficiales de evacuación o refugio."], extra: "El yodo de potasio solo protege la tiroides en ataques radiológicos. Tenerlo no te hace inmune." },
    { id: "terrorist", icon: Crosshair, color: "text-purple-400", bgColor: "bg-purple-500/10", borderColor: "border-purple-500/30", level: "CRÍTICO", title: "Ataque Terrorista (Explosivo / Masivo)", warning: "Puede producirse sin aviso en lugares concurridos: metro, mercados, eventos.", steps: ["Si escuchas una explosión: cúbrete INMEDIATAMENTE en el suelo.", "No mires hacia el origen: segunda explosión es táctica habitual.", "Aléjate en dirección CONTRARIA al origen, agachado.", "No uses el ascensor ni te aglomeres en salidas de emergencia.", "Si hay heridos cerca y es seguro: aplica presión en hemorragias.", "Llama al 112 en cuanto estés en zona segura.", "No difundas rumores ni fotos.", "Obedece estrictamente las instrucciones de seguridad."], extra: "Los ataques en dos fases son táctica documentada. Espera siempre 5 minutos antes de acercarte a ayudar." },
    { id: "tsunami", icon: Waves, color: "text-blue-400", bgColor: "bg-blue-500/10", borderColor: "border-blue-500/30", level: "CRÍTICO", title: "Tsunami", warning: "El mar que se retira repentinamente es la señal más clara. Tienes minutos para actuar.", steps: ["Si el mar retrocede drásticamente o sientes terremoto costero: huye INMEDIATAMENTE.", "Dirígete a zonas elevadas sin detenerte.", "No esperes la alerta oficial: cada segundo cuenta.", "Abandona vehículos si el tráfico se detiene. Ve a pie.", "La primera ola no es la más peligrosa: puede haber múltiples olas.", "No regreses a la costa hasta aviso oficial.", "Si estás en barco en mar abierto: aléjate hacia aguas profundas.", "Escucha la radio de emergencia."], extra: "Un tsunami puede viajar a 800 km/h en aguas profundas. Las olas pueden superar los 30 metros." },
    { id: "earthquake", icon: Mountain, color: "text-amber-500", bgColor: "bg-amber-500/10", borderColor: "border-amber-500/30", level: "ALTO", title: "Terremoto", warning: "Sin aviso previo. El movimiento puede durar de segundos a minutos.", steps: ["AGÁCHATE, CÚBRETE bajo una mesa resistente y SUJÉTATE.", "Aléjate de ventanas, estanterías y paredes exteriores.", "Si estás en exterior: aléjate de edificios y cables eléctricos.", "NO uses el ascensor. NO corras durante el temblor.", "Si estás en cama: quédate, cúbrete la cabeza con la almohada.", "Tras el sismo: corta el gas si hueles fuga.", "Sal del edificio con calma. Busca zona abierta.", "Prepárate para réplicas."], extra: "La regla del triángulo de vida es un mito peligroso. Agáchate bajo una mesa resistente." },
    { id: "wildfire", icon: Flame, color: "text-orange-400", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "ALTO", title: "Incendio Forestal", warning: "Puede avanzar más rápido que un corredor olímpico. La evacuación temprana es la única defensa.", steps: ["Ante alerta en tu zona: evacúa ANTES de que sea obligatorio.", "Cierra puertas y ventanas al salir.", "Sigue rutas de evacuación oficiales. No improvises.", "Si te sorprende en vehículo: aparca, bocina, cúbrete con manta ignífuga.", "Si estás a pie: busca la zona ya quemada.", "Protege las vías respiratorias con tela húmeda.", "Nunca huyas cuesta arriba: el fuego sube más rápido.", "Avisa a bomberos de tu posición cuando sea seguro."], extra: "El humo mata antes que las llamas. Un incendio puede avanzar a 100 km/h con viento fuerte." },
  ],
  en: [
    { id: "missile", icon: Bomb, color: "text-red-500", bgColor: "bg-red-500/10", borderColor: "border-red-500/30", level: "CRITICAL", title: "Ballistic Missile Attack", warning: "You'll have 4 to 14 minutes of warning if an alert system exists.", steps: ["When you hear the siren: don't waste a second looking out the window.", "Go IMMEDIATELY to the basement or lowest interior room.", "Stay away from windows, glass and exterior walls.", "Cover under a sturdy table or against an interior wall.", "If outside: lie flat on the ground, cover your head.", "Do NOT use the elevator. Use the stairs.", "Stay in shelter at least 24h after impact.", "Listen to emergency radio. Do not leave until official clearance."], extra: "Current hypersonic missiles travel at Mach 5+. There will be no time to think. Only to react." },
    { id: "infantry", icon: Users, color: "text-orange-500", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "HIGH", title: "Active Shooter / Infantry Attack", warning: "Can occur without warning in urban areas.", steps: ["RUN: If there's a safe exit, flee leaving everything behind.", "HIDE: If you can't flee, find dense cover.", "Lock doors. Block with heavy furniture.", "Turn off lights. Silence your phone completely.", "Call 911 when safe to do so.", "FIGHT as a last resort: heavy objects, chairs, fire extinguishers.", "Do not move until police confirm the area is clear.", "Raise hands when rescued. Follow exact instructions."], extra: "In active armed conflict, rules change. Discipline is everything." },
    { id: "emp", icon: Zap, color: "text-yellow-500", bgColor: "bg-yellow-500/10", borderColor: "border-yellow-500/30", level: "HIGH", title: "Electromagnetic Pulse (EMP)", warning: "An EMP can disable all electronics within hundreds of kilometers.", steps: ["If all electronics fail at once: assume an EMP. Do not panic.", "Modern vehicles will stop working. Travel on foot.", "Communicate only in person or via analog radios.", "Tap water may fail. Use reserves.", "Keep physical cash: ATMs and card terminals won't work.", "Establish a PRIOR family meeting point. There's no way to call.", "Keep an analog battery radio in your go-bag.", "Hospitals without generators will fail. Activate your medical kit."], extra: "A single nuclear warhead detonated 400km above can shut down the power grid of an entire country." },
    { id: "chemical", icon: Radio, color: "text-green-500", bgColor: "bg-green-500/10", borderColor: "border-green-500/30", level: "SEVERE", title: "Chemical / Radiological Attack", warning: "Invisible, often odorless. Devastating within minutes.", steps: ["Smell of almonds, garlic or rotten eggs: leave the area RUNNING.", "Cover nose and mouth with wet cloth as a temporary measure.", "Seek height: many chemical agents are denser than air.", "Radiological attack: maximize distance from the source.", "Seal windows and doors with tape if you must shelter in place.", "Showering with soap removes up to 80% of external contamination.", "Do not touch victims without protection. You could be contaminated.", "Follow official evacuation or shelter-in-place instructions."], extra: "Potassium iodide only protects the thyroid in radiological attacks. Having it does not make you immune." },
    { id: "terrorist", icon: Crosshair, color: "text-purple-400", bgColor: "bg-purple-500/10", borderColor: "border-purple-500/30", level: "CRITICAL", title: "Terrorist Attack (Explosive / Mass Casualty)", warning: "Can occur without warning in crowded places: subway, markets, events.", steps: ["If you hear an explosion: take cover IMMEDIATELY on the ground.", "Do not look toward the origin: a second blast is a common tactic.", "Move AWAY from the origin, crouched, staying close to walls.", "Do not use elevators or crowd emergency exits.", "If there are nearby injured and it is safe: apply direct pressure.", "Call 911 as soon as you reach a safe area.", "Do not spread rumors or photos.", "Strictly follow instructions from security forces."], extra: "Two-phase attacks are a documented tactic. Always wait 5 minutes before approaching to help." },
    { id: "tsunami", icon: Waves, color: "text-blue-400", bgColor: "bg-blue-500/10", borderColor: "border-blue-500/30", level: "CRITICAL", title: "Tsunami", warning: "The sea suddenly retreating is the clearest warning sign. You have minutes to act.", steps: ["If the sea retreats drastically or you feel a strong coastal earthquake: flee IMMEDIATELY inland.", "Head to high ground without stopping.", "Do not wait for official alerts: every second counts.", "Abandon vehicles if traffic stops. Go on foot.", "The first wave is not the most dangerous: multiple waves can strike.", "Do not return to the coast until official all-clear.", "If on a boat in open sea: move away from shore into deep water.", "Listen to emergency radio."], extra: "A tsunami can travel at 800 km/h in deep water. Waves can exceed 30 meters." },
    { id: "earthquake", icon: Mountain, color: "text-amber-500", bgColor: "bg-amber-500/10", borderColor: "border-amber-500/30", level: "HIGH", title: "Earthquake", warning: "No prior warning. Shaking can last from seconds to minutes.", steps: ["DROP, COVER under a sturdy table, and HOLD ON.", "Stay away from windows, shelves and exterior walls.", "If outdoors: move away from buildings and power lines.", "Do NOT use elevators. Do NOT run during shaking.", "If in bed: stay there, cover your head with a pillow.", "After the quake: shut off gas if you smell a leak.", "Exit the building calmly. Find an open area.", "Prepare for aftershocks."], extra: "The triangle of life rule is a dangerous myth. Drop under a sturdy table." },
    { id: "wildfire", icon: Flame, color: "text-orange-400", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "HIGH", title: "Wildfire", warning: "Can advance faster than an Olympic sprinter. Early evacuation is the only real defense.", steps: ["On wildfire alert in your area: evacuate BEFORE it becomes mandatory.", "Close doors and windows when leaving.", "Follow official evacuation routes. Do not improvise.", "If caught in a vehicle: park, lights on, horn blaring, cover with fire blanket.", "If on foot: seek already-burned area.", "Protect airways with wet cloth.", "Never flee uphill: fire climbs faster than you.", "Alert firefighters of your position when safe."], extra: "Smoke kills before flames do. A wildfire can advance at 100 km/h with strong winds." },
  ],
  fr: [
    { id: "missile", icon: Bomb, color: "text-red-500", bgColor: "bg-red-500/10", borderColor: "border-red-500/30", level: "CRITIQUE", title: "Attaque de missile balistique", warning: "Vous aurez entre 4 et 14 minutes d'avertissement si un système d'alerte existe.", steps: ["En entendant la sirène: ne perdez pas une seconde.", "Allez IMMÉDIATEMENT au sous-sol ou dans la pièce intérieure la plus basse.", "Éloignez-vous des fenêtres, vitres et murs extérieurs.", "Couvrez-vous sous une table solide ou contre un mur intérieur.", "Si vous êtes dehors: allongez-vous au sol, couvrez votre tête.", "N'utilisez PAS l'ascenseur. Utilisez les escaliers.", "Restez à l'abri au moins 24h après l'impact.", "Écoutez la radio d'urgence. Ne sortez pas sans autorisation officielle."], extra: "Les missiles hypersoniques actuels voyagent à Mach 5+. Il n'y aura pas le temps de réfléchir. Seulement de réagir." },
    { id: "infantry", icon: Users, color: "text-orange-500", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "ÉLEVÉ", title: "Tireur actif / Attaque d'infanterie", warning: "Peut survenir sans avertissement dans les zones urbaines.", steps: ["FUYEZ: S'il y a une sortie sûre, fuyez en laissant tout derrière.", "CACHEZ-VOUS: Si vous ne pouvez pas fuir, cherchez une couverture dense.", "Verrouillez les portes. Bloquez avec des meubles lourds.", "Éteignez les lumières. Mettez votre téléphone en mode silencieux.", "Appelez le 17 ou 112 quand c'est sûr.", "COMBATTEZ en dernier recours: objets lourds, chaises, extincteurs.", "Ne bougez pas tant que la police ne confirme pas que la zone est sûre.", "Levez les mains quand vous êtes secouru. Suivez les instructions exactes."], extra: "En conflit armé actif, les règles changent. La discipline est primordiale." },
    { id: "emp", icon: Zap, color: "text-yellow-500", bgColor: "bg-yellow-500/10", borderColor: "border-yellow-500/30", level: "ÉLEVÉ", title: "Impulsion électromagnétique (IEM)", warning: "Une IEM peut neutraliser toute l'électronique dans des centaines de kilomètres.", steps: ["Si toute l'électronique tombe en panne d'un coup: supposez une IEM. Ne paniquez pas.", "Les véhicules modernes s'arrêteront de fonctionner. Déplacez-vous à pied.", "Communiquez uniquement en personne ou via des radios analogiques.", "L'eau du robinet peut tomber en panne. Utilisez vos réserves.", "Gardez de l'argent liquide: les distributeurs et terminaux ne fonctionneront pas.", "Établissez un point de réunion familial PRÉVU à l'avance.", "Gardez une radio analogique à piles dans votre sac d'urgence.", "Les hôpitaux sans générateurs tomberont en panne. Activez votre kit médical."], extra: "Une seule ogive nucléaire détonée à 400km d'altitude peut éteindre le réseau électrique d'un pays entier." },
    { id: "chemical", icon: Radio, color: "text-green-500", bgColor: "bg-green-500/10", borderColor: "border-green-500/30", level: "SÉVÈRE", title: "Attaque chimique / radiologique", warning: "Invisible, souvent inodore. Dévastateur en quelques minutes.", steps: ["Odeur d'amandes, d'ail ou d'œufs pourris: quittez la zone EN COURANT.", "Couvrez nez et bouche avec un tissu humide comme mesure temporaire.", "Cherchez de la hauteur: beaucoup d'agents chimiques sont plus denses que l'air.", "Attaque radiologique: mettez la distance maximale entre vous et la source.", "Scellez fenêtres et portes avec du ruban adhésif si vous devez rester.", "Se doucher au savon élimine jusqu'à 80% de la contamination externe.", "Ne touchez pas les victimes sans protection. Vous pourriez être contaminé.", "Suivez les instructions officielles d'évacuation."], extra: "L'iodure de potassium ne protège que la thyroïde lors d'attaques radiologiques. L'avoir ne vous rend pas immunisé." },
    { id: "terrorist", icon: Crosshair, color: "text-purple-400", bgColor: "bg-purple-500/10", borderColor: "border-purple-500/30", level: "CRITIQUE", title: "Attentat terroriste (explosif / de masse)", warning: "Peut survenir sans avertissement dans les lieux bondés: métro, marchés, événements.", steps: ["Si vous entendez une explosion: mettez-vous immédiatement à couvert au sol.", "Ne regardez pas vers l'origine: une deuxième explosion est une tactique courante.", "Éloignez-vous en direction OPPOSÉE à l'origine, accroupi.", "N'utilisez pas les ascenseurs ni ne vous agglomerez aux sorties de secours.", "S'il y a des blessés proches et que c'est sûr: appliquez une pression directe.", "Appelez le 15 ou 112 dès que vous êtes en zone sûre.", "Ne diffusez pas de rumeurs ni de photos.", "Obéissez strictement aux instructions des forces de sécurité."], extra: "Les attaques en deux phases sont une tactique documentée. Attendez toujours 5 minutes avant d'approcher pour aider." },
    { id: "tsunami", icon: Waves, color: "text-blue-400", bgColor: "bg-blue-500/10", borderColor: "border-blue-500/30", level: "CRITIQUE", title: "Tsunami", warning: "La mer qui se retire brusquement est le signe le plus clair. Vous avez des minutes pour agir.", steps: ["Si la mer recule drastiquement ou vous ressentez un fort séisme côtier: fuyez IMMÉDIATEMENT vers l'intérieur.", "Dirigez-vous vers des zones élevées sans vous arrêter.", "N'attendez pas les alertes officielles: chaque seconde compte.", "Abandonnez les véhicules si la circulation s'arrête. Allez à pied.", "La première vague n'est pas la plus dangereuse: plusieurs vagues peuvent frapper.", "Ne revenez pas sur la côte avant l'autorisation officielle.", "Si vous êtes sur un bateau en mer ouverte: éloignez-vous vers les eaux profondes.", "Écoutez la radio d'urgence."], extra: "Un tsunami peut voyager à 800 km/h en eaux profondes. Les vagues peuvent dépasser 30 mètres." },
    { id: "earthquake", icon: Mountain, color: "text-amber-500", bgColor: "bg-amber-500/10", borderColor: "border-amber-500/30", level: "ÉLEVÉ", title: "Tremblement de terre", warning: "Sans avertissement préalable. Les secousses peuvent durer de secondes à minutes.", steps: ["BAISSEZ-VOUS, COUVREZ-VOUS sous une table solide et TENEZ-VOUS.", "Éloignez-vous des fenêtres, étagères et murs extérieurs.", "Si dehors: éloignez-vous des bâtiments et des lignes électriques.", "N'utilisez PAS l'ascenseur. Ne courez PAS pendant les secousses.", "Si vous êtes au lit: restez-y, couvrez votre tête avec l'oreiller.", "Après le séisme: coupez le gaz si vous sentez une fuite.", "Quittez le bâtiment calmement. Cherchez une zone ouverte.", "Préparez-vous aux répliques."], extra: "La règle du triangle de vie est un mythe dangereux. Baissez-vous sous une table solide." },
    { id: "wildfire", icon: Flame, color: "text-orange-400", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "ÉLEVÉ", title: "Incendie de forêt", warning: "Peut avancer plus vite qu'un sprinter olympique. L'évacuation précoce est la seule vraie défense.", steps: ["En cas d'alerte dans votre zone: évacuez AVANT que ce soit obligatoire.", "Fermez portes et fenêtres en partant.", "Suivez les routes d'évacuation officielles. N'improvisez pas.", "Si surpris en véhicule: garez-vous, klaxon, couvrez-vous avec une couverture ignifuge.", "Si à pied: cherchez une zone déjà brûlée.", "Protégez les voies respiratoires avec un tissu humide.", "Ne fuyez jamais en montant: le feu monte plus vite que vous.", "Signalez votre position aux pompiers quand c'est sûr."], extra: "La fumée tue avant les flammes. Un incendie peut avancer à 100 km/h avec un vent fort." },
  ],
  pt: [
    { id: "missile", icon: Bomb, color: "text-red-500", bgColor: "bg-red-500/10", borderColor: "border-red-500/30", level: "CRÍTICO", title: "Ataque de míssil balístico", warning: "Você terá entre 4 e 14 minutos de aviso se houver sistema de alerta.", steps: ["Ao ouvir a sirene: não perca um segundo.", "Vá IMEDIATAMENTE ao porão ou ao cômodo interior mais baixo.", "Afaste-se de janelas, vidros e paredes externas.", "Abrigue-se sob uma mesa resistente ou junto a uma parede interior.", "Se estiver fora: deite no chão, cubra a cabeça.", "NÃO use o elevador. Use as escadas.", "Permaneça no abrigo pelo menos 24h após o impacto.", "Ouça a rádio de emergência. Não saia sem autorização oficial."], extra: "Os mísseis hipersônicos atuais viajam a Mach 5+. Não haverá tempo para pensar. Apenas para reagir." },
    { id: "infantry", icon: Users, color: "text-orange-500", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "ALTO", title: "Atirador ativo / Ataque de infantaria", warning: "Pode ocorrer sem aviso em áreas urbanas.", steps: ["CORRA: Se houver saída segura, fuja deixando tudo para trás.", "ESCONDA-SE: Se não puder fugir, procure cobertura densa.", "Tranque as portas. Bloqueie com móveis pesados.", "Apague as luzes. Silencie o celular completamente.", "Ligue para o 190 ou 192 quando for seguro.", "LUTE como último recurso: objetos pesados, cadeiras, extintores.", "Não se mova até a confirmação policial de área segura.", "Levante as mãos ao ser resgatado. Siga as instruções exatas."], extra: "Em conflito armado ativo, as regras mudam. A disciplina é tudo." },
    { id: "emp", icon: Zap, color: "text-yellow-500", bgColor: "bg-yellow-500/10", borderColor: "border-yellow-500/30", level: "ALTO", title: "Pulso eletromagnético (PEM)", warning: "Um PEM pode inutilizar toda a eletrônica em centenas de quilômetros.", steps: ["Se toda a eletrônica falhar de uma vez: assuma um PEM. Não entre em pânico.", "Os veículos modernos vão parar de funcionar. Vá a pé.", "Comunique-se apenas pessoalmente ou por rádios analógicas.", "A água da torneira pode falhar. Use reservas.", "Mantenha dinheiro físico: caixas eletrônicos não funcionarão.", "Estabeleça um ponto de encontro familiar PRÉVIO. Não há como ligar.", "Guarde um rádio analógico a pilhas na sua mochila de emergência.", "Hospitais sem geradores vão falhar. Ative seu kit médico."], extra: "Uma única ogiva nuclear detonada a 400km de altitude pode desligar a rede elétrica de um país inteiro." },
    { id: "chemical", icon: Radio, color: "text-green-500", bgColor: "bg-green-500/10", borderColor: "border-green-500/30", level: "SEVERO", title: "Ataque químico / radiológico", warning: "Invisível, muitas vezes inodoro. Devastador em minutos.", steps: ["Cheiro de amêndoas, alho ou ovo podre: abandone a área CORRENDO.", "Cubra nariz e boca com pano úmido como medida temporária.", "Procure altura: muitos agentes químicos são mais densos que o ar.", "Ataque radiológico: maximize a distância da fonte.", "Sele janelas e portas com fita adesiva se precisar ficar.", "Tomar banho com sabão elimina até 80% da contaminação externa.", "Não toque em vítimas sem proteção. Você pode ser contaminado.", "Siga as instruções oficiais de evacuação."], extra: "O iodeto de potássio só protege a tireoide em ataques radiológicos. Tê-lo não o torna imune." },
    { id: "terrorist", icon: Crosshair, color: "text-purple-400", bgColor: "bg-purple-500/10", borderColor: "border-purple-500/30", level: "CRÍTICO", title: "Ataque terrorista (explosivo / massa)", warning: "Pode ocorrer sem aviso em locais lotados: metrô, mercados, eventos.", steps: ["Se ouvir uma explosão: abrigue-se IMEDIATAMENTE no chão.", "Não olhe para a origem: uma segunda explosão é tática comum.", "Afaste-se em direção OPOSTA à origem, agachado.", "Não use elevadores nem se aglomere em saídas de emergência.", "Se há feridos perto e é seguro: aplique pressão direta nas hemorragias.", "Ligue para o 190 assim que estiver em área segura.", "Não espalhe rumores nem fotos.", "Obedeça estritamente às instruções das forças de segurança."], extra: "Ataques em duas fases são tática documentada. Sempre espere 5 minutos antes de se aproximar para ajudar." },
    { id: "tsunami", icon: Waves, color: "text-blue-400", bgColor: "bg-blue-500/10", borderColor: "border-blue-500/30", level: "CRÍTICO", title: "Tsunami", warning: "O mar que recua repentinamente é o sinal mais claro. Você tem minutos para agir.", steps: ["Se o mar recuar drasticamente ou você sentir um forte terremoto costeiro: fuja IMEDIATAMENTE para o interior.", "Dirija-se a zonas elevadas sem parar.", "Não espere alertas oficiais: cada segundo conta.", "Abandone veículos se o trânsito parar. Vá a pé.", "A primeira onda não é a mais perigosa: podem vir várias ondas.", "Não volte à costa até aviso oficial.", "Se estiver em barco em mar aberto: afaste-se para águas profundas.", "Ouça a rádio de emergência."], extra: "Um tsunami pode viajar a 800 km/h em águas profundas. As ondas podem ultrapassar 30 metros." },
    { id: "earthquake", icon: Mountain, color: "text-amber-500", bgColor: "bg-amber-500/10", borderColor: "border-amber-500/30", level: "ALTO", title: "Terremoto", warning: "Sem aviso prévio. O tremor pode durar de segundos a minutos.", steps: ["AGACHE-SE, CUBRA-SE sob uma mesa resistente e SEGURE-SE.", "Afaste-se de janelas, estantes e paredes externas.", "Se estiver fora: afaste-se de edifícios e fios elétricos.", "NÃO use o elevador. NÃO corra durante o tremor.", "Se estiver na cama: fique, cubra a cabeça com o travesseiro.", "Após o sismo: feche o gás se sentir vazamento.", "Saia do edifício com calma. Procure área aberta.", "Prepare-se para réplicas."], extra: "A regra do triângulo da vida é um mito perigoso. Agache-se sob uma mesa resistente." },
    { id: "wildfire", icon: Flame, color: "text-orange-400", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "ALTO", title: "Incêndio florestal", warning: "Pode avançar mais rápido do que um corredor olímpico. A evacuação precoce é a única defesa real.", steps: ["Em alerta na sua zona: evacue ANTES de ser obrigatório.", "Feche portas e janelas ao sair.", "Siga rotas de evacuação oficiais. Não improvise.", "Se surpreendido em veículo: estacione, buzine, cubra-se com cobertor ignífugo.", "Se a pé: procure área já queimada.", "Proteja as vias respiratórias com pano úmido.", "Nunca fuja subindo: o fogo sobe mais rápido.", "Avise os bombeiros da sua posição quando for seguro."], extra: "A fumaça mata antes das chamas. Um incêndio pode avançar a 100 km/h com vento forte." },
  ],
  it: [
    { id: "missile", icon: Bomb, color: "text-red-500", bgColor: "bg-red-500/10", borderColor: "border-red-500/30", level: "CRITICO", title: "Attacco con missile balistico", warning: "Avrai tra 4 e 14 minuti di preavviso se esiste un sistema di allerta.", steps: ["Sentendo la sirena: non perdere un secondo.", "Vai IMMEDIATAMENTE nel seminterrato o nella stanza più bassa.", "Allontanati da finestre, vetri e pareti esterne.", "Copriti sotto un tavolo robusto o vicino a un muro interno.", "Se sei all'esterno: stenditi a terra, copriti la testa.", "NON usare l'ascensore. Usa le scale.", "Rimani al riparo almeno 24h dopo l'impatto.", "Ascolta la radio di emergenza. Non uscire senza autorizzazione ufficiale."], extra: "I missili ipersonici attuali viaggiano a Mach 5+. Non ci sarà tempo per pensare. Solo per reagire." },
    { id: "infantry", icon: Users, color: "text-orange-500", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "ALTO", title: "Tiratore attivo / Attacco di fanteria", warning: "Può accadere senza preavviso nelle aree urbane.", steps: ["SCAPPA: Se c'è un'uscita sicura, fuggi lasciando tutto.", "NASCONDITI: Se non puoi fuggire, cerca una copertura densa.", "Chiudi le porte a chiave. Blocca con mobili pesanti.", "Spegni le luci. Silenzia completamente il telefono.", "Chiama il 112 quando è sicuro.", "COMBATTI come ultima risorsa: oggetti pesanti, sedie, estintori.", "Non muoverti fino alla conferma della polizia che la zona è sicura.", "Alza le mani quando sei soccorso. Segui le istruzioni esatte."], extra: "In conflitto armato attivo, le regole cambiano. La disciplina è tutto." },
    { id: "emp", icon: Zap, color: "text-yellow-500", bgColor: "bg-yellow-500/10", borderColor: "border-yellow-500/30", level: "ALTO", title: "Impulso elettromagnetico (EMP)", warning: "Un EMP può neutralizzare tutta l'elettronica in centinaia di chilometri.", steps: ["Se tutta l'elettronica si guasta all'improvviso: supponi un EMP. Non farti prendere dal panico.", "I veicoli moderni smetteranno di funzionare. Spostati a piedi.", "Comunica solo di persona o tramite radio analogiche.", "L'acqua del rubinetto potrebbe mancare. Usa le riserve.", "Tieni contanti fisici: i bancomat non funzioneranno.", "Stabilisci un punto d'incontro familiare PREVENTIVO.", "Tieni una radio analogica a batterie nello zaino di emergenza.", "Gli ospedali senza generatori si fermeranno. Attiva il tuo kit medico."], extra: "Una singola testata nucleare detonata a 400km di quota può spegnere la rete elettrica di un intero paese." },
    { id: "chemical", icon: Radio, color: "text-green-500", bgColor: "bg-green-500/10", borderColor: "border-green-500/30", level: "GRAVE", title: "Attacco chimico / radiologico", warning: "Invisibile, spesso inodore. Devastante in pochi minuti.", steps: ["Odore di mandorle, aglio o uova marce: abbandona la zona DI CORSA.", "Copri naso e bocca con un panno umido come misura temporanea.", "Cerca punti elevati: molti agenti chimici sono più pesanti dell'aria.", "Attacco radiologico: massimizza la distanza dalla fonte.", "Sigilla finestre e porte con nastro adesivo se devi restare.", "Fare la doccia con sapone elimina fino all'80% della contaminazione esterna.", "Non toccare le vittime senza protezione. Potresti contaminarti.", "Segui le istruzioni ufficiali di evacuazione."], extra: "Lo ioduro di potassio protegge solo la tiroide negli attacchi radiologici. Averlo non ti rende immune." },
    { id: "terrorist", icon: Crosshair, color: "text-purple-400", bgColor: "bg-purple-500/10", borderColor: "border-purple-500/30", level: "CRITICO", title: "Attentato terroristico (esplosivo / di massa)", warning: "Può avvenire senza preavviso in luoghi affollati: metro, mercati, eventi.", steps: ["Se senti un'esplosione: mettiti IMMEDIATAMENTE al riparo a terra.", "Non guardare verso l'origine: una seconda esplosione è tattica comune.", "Allontanati in direzione OPPOSTA all'origine, accucciato.", "Non usare ascensori né affollarti alle uscite di emergenza.", "Se ci sono feriti vicini ed è sicuro: applica pressione diretta sulle emorragie.", "Chiama il 112 appena sei in zona sicura.", "Non diffondere voci né foto.", "Obbedisci strettamente alle istruzioni delle forze di sicurezza."], extra: "Gli attacchi in due fasi sono una tattica documentata. Aspetta sempre 5 minuti prima di avvicinarti per aiutare." },
    { id: "tsunami", icon: Waves, color: "text-blue-400", bgColor: "bg-blue-500/10", borderColor: "border-blue-500/30", level: "CRITICO", title: "Tsunami", warning: "Il mare che si ritira improvvisamente è il segnale più chiaro. Hai minuti per agire.", steps: ["Se il mare si ritira drasticamente o senti un forte terremoto costiero: fuggi IMMEDIATAMENTE verso l'interno.", "Dirigiti verso zone elevate senza fermarti.", "Non aspettare gli avvisi ufficiali: ogni secondo conta.", "Abbandona i veicoli se il traffico si ferma. Vai a piedi.", "La prima onda non è la più pericolosa: potrebbero arrivarne molte.", "Non tornare sulla costa fino all'autorizzazione ufficiale.", "Se sei su un'imbarcazione in mare aperto: allontanati verso acque profonde.", "Ascolta la radio di emergenza."], extra: "Uno tsunami può viaggiare a 800 km/h in acque profonde. Le onde possono superare i 30 metri." },
    { id: "earthquake", icon: Mountain, color: "text-amber-500", bgColor: "bg-amber-500/10", borderColor: "border-amber-500/30", level: "ALTO", title: "Terremoto", warning: "Senza preavviso. Le scosse possono durare da secondi a minuti.", steps: ["ABBASSATI, COPRITI sotto un tavolo robusto e TIENITI.", "Allontanati da finestre, scaffali e pareti esterne.", "Se sei all'esterno: allontanati da edifici e linee elettriche.", "NON usare l'ascensore. NON correre durante le scosse.", "Se sei a letto: restaci, copriti la testa con il cuscino.", "Dopo il sisma: chiudi il gas se senti una perdita.", "Esci dall'edificio con calma. Cerca un'area aperta.", "Preparati alle repliche."], extra: "La regola del triangolo della vita è un mito pericoloso. Abbassati sotto un tavolo robusto." },
    { id: "wildfire", icon: Flame, color: "text-orange-400", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "ALTO", title: "Incendio boschivo", warning: "Può avanzare più velocemente di un corridore olimpico. L'evacuazione precoce è l'unica vera difesa.", steps: ["In caso di allerta nella tua zona: evacua PRIMA che diventi obbligatorio.", "Chiudi porte e finestre prima di uscire.", "Segui le vie di evacuazione ufficiali. Non improvvisare.", "Se sorpreso in veicolo: parcheggia, clacson, copriti con una coperta ignifuga.", "Se a piedi: cerca una zona già bruciata.", "Proteggi le vie respiratorie con un panno umido.", "Non fuggire mai in salita: il fuoco sale più veloce di te.", "Avvisa i vigili del fuoco della tua posizione quando è sicuro."], extra: "Il fumo uccide prima delle fiamme. Un incendio può avanzare a 100 km/h con vento forte." },
  ],
  ar: [
    { id: "missile", icon: Bomb, color: "text-red-500", bgColor: "bg-red-500/10", borderColor: "border-red-500/30", level: "حرج", title: "هجوم صاروخي باليستي", warning: "سيكون لديك بين 4 و14 دقيقة من التحذير المسبق إذا كان هناك نظام إنذار.", steps: ["عند سماع صفارة الإنذار: لا تضيع ثانية واحدة.", "اذهب فوراً إلى القبو أو أدنى غرفة داخلية.", "ابتعد عن النوافذ والزجاج والجدران الخارجية.", "اختبئ تحت طاولة متينة أو بجانب جدار داخلي.", "إذا كنت في الخارج: استلقِ على الأرض وغطِّ رأسك.", "لا تستخدم المصعد. استخدم الدرج.", "ابق في الملجأ على الأقل 24 ساعة بعد الاصطدام.", "استمع إلى راديو الطوارئ. لا تخرج دون إذن رسمي."], extra: "الصواريخ ال극음속الحالية تسافر بسرعة ماخ 5+. لن يكون هناك وقت للتفكير. فقط للتصرف." },
    { id: "infantry", icon: Users, color: "text-orange-500", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "مرتفع", title: "مطلق نار نشط / هجوم مشاة", warning: "يمكن أن يحدث دون سابق إنذار في المناطق الحضرية.", steps: ["اركض: إذا كان هناك مخرج آمن، فر تاركاً كل شيء.", "اختبئ: إذا لم تستطع الفرار، ابحث عن غطاء كثيف.", "أغلق الأبواب بالمفتاح. أعقها بأثاث ثقيل.", "أطفئ الأضواء. أسكت هاتفك تماماً.", "اتصل بالطوارئ عندما يكون آمناً.", "قاتل كملاذ أخير: أشياء ثقيلة، كراسي، طفايات حريق.", "لا تتحرك حتى تتأكد الشرطة من أمان المنطقة.", "ارفع يديك عند إنقاذك. اتبع التعليمات بدقة."], extra: "في النزاع المسلح النشط، القواعد تتغير. الانضباط هو كل شيء." },
    { id: "emp", icon: Zap, color: "text-yellow-500", bgColor: "bg-yellow-500/10", borderColor: "border-yellow-500/30", level: "مرتفع", title: "النبضة الكهرومغناطيسية (EMP)", warning: "يمكن للـ EMP تعطيل جميع الإلكترونيات في مئات الكيلومترات.", steps: ["إذا فشلت جميع الإلكترونيات دفعة واحدة: افترض وجود EMP. لا تذعر.", "المركبات الحديثة ستتوقف عن العمل. تنقل سيراً على الأقدام.", "تواصل فقط شخصياً أو عبر أجهزة الراديو التماثلية.", "قد تنقطع مياه الصنبور. استخدم احتياطياتك.", "احتفظ بنقود ورقية: أجهزة الصرف الآلي لن تعمل.", "حدد نقطة تجمع عائلية مسبقاً. لا توجد طريقة للاتصال.", "احتفظ براديو تماثلي يعمل بالبطاريات في حقيبة الطوارئ.", "المستشفيات بدون مولدات ستفشل. فعّل مجموعتك الطبية."], extra: "رأس حربي نووي واحد ينفجر على ارتفاع 400 كم يمكنه إغلاق شبكة الكهرباء لبلد بأكمله." },
    { id: "chemical", icon: Radio, color: "text-green-500", bgColor: "bg-green-500/10", borderColor: "border-green-500/30", level: "شديد", title: "هجوم كيميائي / إشعاعي", warning: "غير مرئي، عديم الرائحة في كثير من الأحيان. مدمر في دقائق.", steps: ["رائحة اللوز أو الثوم أو البيض الفاسد: اترك المنطقة جرياً.", "غطِّ أنفك وفمك بقماش مبلل كإجراء مؤقت.", "ابحث عن الارتفاع: كثير من العوامل الكيميائية أثقل من الهواء.", "هجوم إشعاعي: ضع أقصى مسافة بينك وبين المصدر.", "أغلق النوافذ والأبواب بشريط لاصق إذا اضطررت للبقاء.", "الاستحمام بالصابون يزيل ما يصل إلى 80% من التلوث الخارجي.", "لا تلمس الضحايا بدون حماية. قد تتلوث.", "اتبع تعليمات الإخلاء الرسمية."], extra: "يوديد البوتاسيوم يحمي الغدة الدرقية فقط في الهجمات الإشعاعية. امتلاكه لا يجعلك محصناً." },
    { id: "terrorist", icon: Crosshair, color: "text-purple-400", bgColor: "bg-purple-500/10", borderColor: "border-purple-500/30", level: "حرج", title: "هجوم إرهابي (متفجرات / جماعي)", warning: "يمكن أن يحدث دون إنذار في الأماكن المزدحمة: مترو، أسواق، فعاليات.", steps: ["إذا سمعت انفجاراً: اختبئ فوراً على الأرض.", "لا تنظر نحو مصدر الانفجار: الانفجار الثاني تكتيك شائع.", "ابتعد في الاتجاه المعاكس للمصدر، منحنياً.", "لا تستخدم المصاعد ولا تتزاحم عند مخارج الطوارئ.", "إذا كان هناك جرحى قريبون وكان آمناً: اضغط مباشرة على النزيف الشديد.", "اتصل بالطوارئ فور وصولك لمنطقة آمنة.", "لا تنشر شائعات أو صوراً.", "أطع تعليمات قوات الأمن بدقة."], extra: "الهجمات على مرحلتين تكتيك موثق. انتظر دائماً 5 دقائق قبل الاقتراب للمساعدة." },
    { id: "tsunami", icon: Waves, color: "text-blue-400", bgColor: "bg-blue-500/10", borderColor: "border-blue-500/30", level: "حرج", title: "تسونامي", warning: "البحر الذي يتراجع فجأة هو أوضح إشارة. لديك دقائق للتصرف.", steps: ["إذا تراجع البحر بشكل كبير أو شعرت بزلزال ساحلي قوي: فر فوراً نحو الداخل.", "اتجه نحو المناطق المرتفعة دون توقف.", "لا تنتظر التحذيرات الرسمية: كل ثانية تهم.", "اترك المركبات إذا توقفت حركة المرور. امشِ على الأقدام.", "الموجة الأولى ليست الأكثر خطورة: قد تتبعها موجات متعددة.", "لا تعد إلى الشاطئ حتى صدور إذن رسمي.", "إذا كنت على قارب في البحر المفتوح: ابتعد نحو المياه العميقة.", "استمع إلى راديو الطوارئ."], extra: "يمكن للتسونامي السفر بسرعة 800 كم/ساعة في المياه العميقة. يمكن أن تتجاوز الأمواج 30 متراً." },
    { id: "earthquake", icon: Mountain, color: "text-amber-500", bgColor: "bg-amber-500/10", borderColor: "border-amber-500/30", level: "مرتفع", title: "زلزال", warning: "بدون إنذار مسبق. يمكن أن تستمر الهزات من ثوانٍ إلى دقائق.", steps: ["انحنِ، اختبئ تحت طاولة متينة وتمسك.", "ابتعد عن النوافذ والرفوف والجدران الخارجية.", "إذا كنت في الخارج: ابتعد عن المباني وخطوط الكهرباء.", "لا تستخدم المصعد. لا تركض أثناء الاهتزاز.", "إذا كنت في الفراش: ابقَ فيه، غطِّ رأسك بالوسادة.", "بعد الزلزال: أغلق الغاز إذا شممت تسرباً.", "اخرج من المبنى بهدوء. ابحث عن منطقة مفتوحة.", "استعد للهزات الارتدادية."], extra: "قاعدة مثلث الحياة أسطورة خطيرة. انحنِ تحت طاولة متينة." },
    { id: "wildfire", icon: Flame, color: "text-orange-400", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "مرتفع", title: "حريق الغابات", warning: "يمكن أن يتقدم أسرع من عداء أولمبي. الإخلاء المبكر هو الدفاع الحقيقي الوحيد.", steps: ["عند الإنذار في منطقتك: أخلِ قبل أن يصبح إلزامياً.", "أغلق الأبواب والنوافذ عند المغادرة.", "اتبع طرق الإخلاء الرسمية. لا ترتجل.", "إذا فاجأك الحريق في المركبة: أوقفها، شغّل البوق، تغطَّ ببطانية مقاومة للحريق.", "إذا كنت سيراً: ابحث عن منطقة محترقة مسبقاً.", "احمِ مجرى هوائك بقماش رطب.", "لا تهرب أبداً صعوداً: النار تصعد أسرع منك.", "أخبر رجال الإطفاء بموقعك عندما يكون آمناً."], extra: "الدخان يقتل قبل النيران. يمكن للحريق أن يتقدم بسرعة 100 كم/ساعة مع رياح قوية." },
  ],
  zh: [
    { id: "missile", icon: Bomb, color: "text-red-500", bgColor: "bg-red-500/10", borderColor: "border-red-500/30", level: "危急", title: "弹道导弹袭击", warning: "如果有预警系统，你将有4到14分钟的预警时间。", steps: ["听到警报：不要浪费一秒钟往窗外看。", "立即前往地下室或最低的内部房间。", "远离窗户、玻璃和外墙。", "躲在坚固的桌子下或靠着内墙。", "如果在室外：趴在地上，保护头部。", "不要使用电梯。使用楼梯。", "冲击后在掩体中至少待24小时。", "收听应急广播。未获官方许可不要外出。"], extra: "现代超音速导弹以5倍以上音速飞行。没有时间思考，只有时间反应。" },
    { id: "infantry", icon: Users, color: "text-orange-500", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "高", title: "活跃枪手 / 步兵袭击", warning: "可能在城市地区毫无预警地发生。", steps: ["跑：如果有安全出口，留下所有东西逃跑。", "躲：如果无法逃跑，寻找厚实的掩护物。", "锁上门。用重家具堵住。", "关灯。将手机完全静音。", "安全时拨打紧急电话110/120。", "作为最后手段战斗：重物、椅子、灭火器。", "等警方确认区域安全前不要移动。", "被救援时举起双手。严格按照指示行动。"], extra: "在活跃武装冲突中，规则改变了。纪律就是一切。" },
    { id: "emp", icon: Zap, color: "text-yellow-500", bgColor: "bg-yellow-500/10", borderColor: "border-yellow-500/30", level: "高", title: "电磁脉冲（EMP）", warning: "EMP可以使数百公里内的所有电子设备失效。", steps: ["如果所有电子设备同时失效：假设是EMP。不要惊慌。", "现代车辆将停止工作。步行出行。", "只通过面对面或模拟无线电进行通信。", "自来水可能中断。使用储备。", "保留现金：ATM和刷卡机将不工作。", "事先建立家庭集合点。无法打电话。", "在应急包中备一台模拟调频收音机。", "没有发电机的医院将瘫痪。启动你的医疗包。"], extra: "在400公里高空引爆的单枚核弹头可以关闭整个国家的电网。" },
    { id: "chemical", icon: Radio, color: "text-green-500", bgColor: "bg-green-500/10", borderColor: "border-green-500/30", level: "严重", title: "化学/放射性袭击", warning: "无形，通常无味。数分钟内造成破坏。", steps: ["闻到杏仁、大蒜或臭鸡蛋气味：立即跑离该区域。", "用湿布临时遮住鼻子和嘴巴。", "寻找高处：许多化学制剂比空气更重。", "放射性袭击：与源头保持最大距离。", "如果必须留在原地，用胶带密封窗户和门。", "用肥皂洗澡可去除高达80%的外部污染。", "未经防护不要触摸伤亡人员，可能被污染。", "遵循官方疏散指示。"], extra: "碘化钾在放射性袭击中只保护甲状腺。拥有它并不能让你免疫。" },
    { id: "terrorist", icon: Crosshair, color: "text-purple-400", bgColor: "bg-purple-500/10", borderColor: "border-purple-500/30", level: "危急", title: "恐怖袭击（爆炸/大规模伤亡）", warning: "可能在拥挤场所毫无预警发生：地铁、市场、活动。", steps: ["听到爆炸声：立即趴在地上掩护。", "不要看向爆炸源：第二次爆炸是常见战术。", "弯腰朝相反方向移动，贴近墙壁。", "不要使用电梯，不要在紧急出口拥挤。", "如附近有伤者且安全：对严重出血处直接施压。", "到达安全区域后拨打120/110。", "不要传播谣言或照片。", "严格遵守安全部队的指示。"], extra: "两阶段袭击是有据可查的战术。靠近帮助前始终等待5分钟。" },
    { id: "tsunami", icon: Waves, color: "text-blue-400", bgColor: "bg-blue-500/10", borderColor: "border-blue-500/30", level: "危急", title: "海啸", warning: "海水突然退潮是最明显的警示。你有几分钟的时间采取行动。", steps: ["如果海水急剧退潮或感受到强烈沿海地震：立即向内陆逃跑。", "不停歇地前往高地。", "不要等待官方警报：每一秒都至关重要。", "如果交通停滞就弃车步行。", "第一波海浪不是最危险的：可能有多波海浪。", "未获官方解除警报前不要返回海岸。", "如果在公海上的船只：驶向深水区远离海岸。", "收听应急广播。"], extra: "海啸在深水中可达800公里/小时。海浪高度可超过30米。" },
    { id: "earthquake", icon: Mountain, color: "text-amber-500", bgColor: "bg-amber-500/10", borderColor: "border-amber-500/30", level: "高", title: "地震", warning: "无预警。震动可持续数秒至数分钟。", steps: ["趴下、在坚固桌子下躲避并抓牢。", "远离窗户、书架和外墙。", "如在户外：远离建筑物和电线。", "不要使用电梯。震动时不要奔跑。", "如果在床上：留在床上，用枕头保护头部。", "地震后：如闻到泄漏就关掉煤气。", "镇定地撤出建筑。找到开阔地带。", "为余震做好准备。"], extra: "生命三角理论是危险的谬论。在坚固的桌子下趴下才是经过科学验证的方法。" },
    { id: "wildfire", icon: Flame, color: "text-orange-400", bgColor: "bg-orange-500/10", borderColor: "border-orange-500/30", level: "高", title: "山火", warning: "蔓延速度可能超过奥运短跑运动员。早期疏散是唯一真正的防御。", steps: ["收到所在区域的山火警报：在强制疏散之前撤离。", "离开时关好门窗。", "遵循官方疏散路线。不要临时发挥。", "如被困在车内：停车、鸣笛、用防火毯盖住自己。", "如步行：寻找已经燃烧过的区域。", "用湿布保护呼吸道。", "永远不要向上坡逃跑：火势上坡比你快。", "安全时通知消防人员你的位置。"], extra: "烟雾在火焰之前就能致命。在强风中山火可以100公里/小时的速度蔓延。" },
  ],
};

export default function Threats() {
  const { lang } = useLang();
  const ui = uiLabels[lang] || uiLabels["en"];
  const threats = threatData[lang] || threatData["en"];
  const [openId, setOpenId] = useState("missile");

  return (
    <div className="max-w-3xl mx-auto px-6 py-10">
      <div className="flex items-center gap-2 mb-2">
        <div className="w-2 h-2 bg-red-500 rounded-full alert-pulse" />
        <span className="text-red-500 text-xs font-bold tracking-widest uppercase">{ui.tagline}</span>
      </div>
      <h1 className="font-military text-3xl lg:text-4xl text-foreground tracking-widest mb-2">{ui.title}</h1>
      <p className="text-muted-foreground text-sm mb-8 leading-relaxed">{ui.subtitle}</p>

      <div className="space-y-3">
        {threats.map((threat) => {
          const Icon = threat.icon;
          const isOpen = openId === threat.id;
          return (
            <div key={threat.id} className={`border rounded overflow-hidden ${threat.borderColor}`}>
              <button onClick={() => setOpenId(isOpen ? null : threat.id)} className={`w-full flex items-center justify-between p-5 ${threat.bgColor} hover:opacity-90 transition-all`}>
                <div className="flex items-center gap-4">
                  <Icon className={`w-6 h-6 ${threat.color}`} />
                  <div className="text-left">
                    <div className={`text-[10px] font-bold tracking-widest ${threat.color} mb-0.5`}>{ui.levelLabel}: {threat.level}</div>
                    <div className="font-military text-sm text-foreground tracking-wide">{threat.title}</div>
                  </div>
                </div>
                {isOpen ? <ChevronUp className="w-4 h-4 text-muted-foreground" /> : <ChevronDown className="w-4 h-4 text-muted-foreground" />}
              </button>
              {isOpen && (
                <div className="p-5 bg-card border-t border-border">
                  <div className="flex items-start gap-2 mb-5 p-3 bg-accent/10 border border-accent/30 rounded">
                    <AlertTriangle className="w-4 h-4 text-accent mt-0.5 shrink-0" />
                    <p className="text-xs text-accent leading-relaxed">{threat.warning}</p>
                  </div>
                  <h3 className="text-xs font-bold text-muted-foreground tracking-widest uppercase mb-3">{ui.protocolLabel}</h3>
                  <ol className="space-y-2 mb-5">
                    {threat.steps.map((step, i) => (
                      <li key={i} className="flex items-start gap-3">
                        <span className="text-primary font-military text-sm font-bold shrink-0 w-5">{i + 1}.</span>
                        <span className="text-sm text-foreground leading-relaxed">{step}</span>
                      </li>
                    ))}
                  </ol>
                  <div className="p-3 bg-secondary rounded border border-border">
                    <div className="flex items-center gap-2 mb-1">
                      <Shield className="w-3 h-3 text-muted-foreground" />
                      <span className="text-[10px] text-muted-foreground uppercase tracking-widest font-bold">{ui.noteLabel}</span>
                    </div>
                    <p className="text-xs text-muted-foreground italic leading-relaxed">{threat.extra}</p>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
